trinodb/docker-images

- prestodb/centos6-oj8/Dockerfile
Fixes https://github.com/prestosql/docker-images/issues/2
> Install sudo

- prestodev/centos7-oj8/Dockerfile
- prestodev/hdp3.1-hive-kerberized/files/etc/hive/conf/hive-site.xml
- prestodev/hdp3.1-hive/files/etc/hive/conf/hive-site.xml
This is required to run a compaction.
> Enable compactor in metastore

- prestodev/centos6-oj8/Dockerfile
- prestodev/centos7-oj8/Dockerfile
Fix Unicode rendering in e.g. Preto CLI's pager when using product
tests environment interactively.
Alternative to https://github.com/prestosql/presto/pull/1904
> Fix Unicode rendering in some programs

- .travis.yml
Test if prestodev/hdp2.6-hive-kerberized-2 builds
> Test if prestodev/hdp2.6-hive-kerberized-2 builds

- prestodev/centos7-oj11/Dockerfile
> Add centos7-oj11

- .travis.yml
> Run more builds in Travis

- prestodev/centos6-presto-admin-tests-runtime/Dockerfile
Disable unstable yum mirrors.iuscommunity.org repo
> Disable unstable yum mirrors.iuscommunity.org repo

- .travis.yml
- bin/test_kerberos.sh
- prestodev/kerberos/Dockerfile
- prestodev/kerberos/files/etc/krb5.conf
- prestodev/kerberos/files/etc/supervisord.conf
- prestodev/kerberos/files/etc/supervisord.d/kdc.conf
- prestodev/kerberos/files/opt/entrypoint.sh
- prestodev/kerberos/files/usr/local/bin/create_principal
- prestodev/kerberos/files/var/kerberos/krb5kdc/kadm5-other.acl
- prestodev/kerberos/files/var/kerberos/krb5kdc/kadm5.acl
- prestodev/kerberos/files/var/kerberos/krb5kdc/kdc.conf
Add dedicated image for Kerberos
> Add dedicated image for Kerberos

- prestodev/cdh5.12-hive-kerberized/files/etc/krb5.conf
- prestodev/cdh5.15-hive-kerberized/files/etc/krb5.conf
- prestodev/hdp2.5-hive-kerberized/files/etc/krb5.conf
- prestodev/hdp2.6-hive-kerberized-2/files/etc/krb5.conf
- prestodev/hdp2.6-hive-kerberized/files/etc/krb5.conf
- prestodev/hdp3.1-hive-kerberized/files/etc/krb5.conf
- prestodev/kerberos/files/etc/krb5.conf
Remove KRB ticket lifetime options
> Remove KRB ticket lifetime options

- prestodev/centos6-oj8-openldap/Dockerfile
Depends on https://github.com/prestosql/presto/pull/3523
> Do not modify default trust store for JDK

- prestodev/kerberos/files/opt/entrypoint.sh
Supersedes #56 
Co-authored-by: Łukasz Walkiewicz <lukasz.walkiewicz@starburstdata.com>
> Allow running multiple bootstrap commands in Krb

- prestodev/cdh5.12-hive-kerberized/Dockerfile
- prestodev/cdh5.15-hive-kerberized/Dockerfile
- prestodev/hdp2.6-hive-kerberized-2/Dockerfile
- prestodev/hdp2.6-hive-kerberized/Dockerfile
- prestodev/hdp3.1-hive-kerberized/Dockerfile
We could also change Kerberos principals as well (and rename presto-master to trino-master/coordinator). WDYT @findepi ?
> Create keytabs in /etc/trino

- Makefile
The MakeFile is updated to push the images to GHCR
> Push the images to GHCR

- testing/centos7-oj11/Dockerfile
Add handy jq tool for json processing - needed for testing improvements (lightweight ~170kB).
> Add jq to centos7-oj11 docker image

- .github/workflows/ci.yml
- testing/spark3-delta/Dockerfile
In hindsight to open sourcing the Delta Lake tests, we need to open source the spark delta image as well.
> Add spark3-delta image

- testing/spark3-delta/Dockerfile
Relates to https://github.com/trinodb/trino/pull/12590
> Upgrade to Spark 3.2.1 and Delta 1.2.1 in spark3-delta

- testing/hdp3.1-hive-kerberized-2/Dockerfile
- testing/hdp3.1-hive-kerberized-2/files/etc/hive/conf/hiveserver2-site.xml
- testing/hdp3.1-hive-kerberized-2/files/etc/krb5.conf
- testing/hdp3.1-hive-kerberized-2/files/etc/supervisord.d/kdc.conf
- testing/hdp3.1-hive-kerberized-2/files/overrides/etc/hadoop/conf/core-site.xml
- testing/hdp3.1-hive-kerberized-2/files/overrides/etc/hadoop/conf/hdfs-site.xml
- testing/hdp3.1-hive-kerberized-2/files/overrides/etc/hadoop/conf/mapred-site.xml
- testing/hdp3.1-hive-kerberized-2/files/overrides/etc/hadoop/conf/yarn-site.xml
- testing/hdp3.1-hive-kerberized-2/files/overrides/etc/hive/conf/hive-site.xml
- testing/hdp3.1-hive-kerberized-2/files/var/kerberos/krb5kdc/kadm5-other.acl
- testing/hdp3.1-hive-kerberized-2/files/var/kerberos/krb5kdc/kadm5.acl
- testing/hdp3.1-hive-kerberized-2/files/var/kerberos/krb5kdc/kdc.conf
Copied from `hdp2.6-hive-kerberized-2`.
> Add kerberized-2 variant for hdp3

- bin/test.sh
Turns out `docker compose ps --format json` produces a single object, not a list.
> Fix accumulo tests

- .github/workflows/release.yml
- bin/test.sh
Fix release job failure https://github.com/trinodb/docker-images/actions/runs/8506505211/job/23296807798
> Remove Greenplum release step and tests

- build/sphinx/requirements.in
- build/sphinx/requirements.txt
Following package version bumps have been done in `requirements.in` and corresponding auto updates are done in `requirements.txt`
| Package     | old_version | new_version |
|-------------|-------------|-------------|
| sphinx      | 7.3.7       | 8.2.3       |
| myst_parser | 2.0.0       | 4.0.1       |
| markupsafe  | 2.1.5       | 3.0.2       |
> Switch sphinx theme to immaterial

- testing/polaris-catalog/Dockerfile
Relates to https://github.com/apache/polaris/pull/1695
> Fix build command in Polaris
