prestodb/centos6-oj8/Dockerfile

`supervisord` drop support for Python 2.6 in
https://github.com/Supervisor/supervisor/pull/1029

Pin supervisord for Python 2.6

---

Makefile
README.md

`docker-release` usage was removed in
a4170f2ddd5b4b501df3376b7197894eeef9747f.

Remove traces of docker-release

---

prestodev/centos6-oj8/Dockerfile
prestodev/centos7-oj8/Dockerfile
prestodev/hdp2.6-hive-kerberized/Dockerfile
prestodev/hdp2.6-hive/Dockerfile
prestodev/hdp3.1-hive-kerberized/Dockerfile
prestodev/hdp3.1-hive-kerberized/files/etc/hive/conf/hive-site.xml
prestodev/hdp3.1-hive/Dockerfile
prestodev/hdp3.1-hive/files/etc/hive/conf/hive-site.xml

Developer convenience improvements

---

prestodev/hdp3.1-hive-kerberized/files/etc/hive/conf/hive-site.xml
prestodev/hdp3.1-hive/files/etc/hive/conf/hive-site.xml

Without the change, the call fails with
```
MetaException: java.lang.UnsupportedOperationException: Storage schema reading not supported
```

Fix Metastore get_fields in HDP 3.1

---

prestodev/hdp3.1-hive/files/etc/tez/conf/tez-site.xml

According to https://bugs.openjdk.java.net/browse/JDK-8189922 the flag
may not be safe in dockerized environment.

Remove -XX:+UseNUMA flag

---

prestodev/cdh5.12-hive/files/root/setup.sh
prestodev/cdh5.15-hive/files/root/setup.sh
prestodev/hdp2.5-hive/files/root/setup.sh
prestodev/hdp2.6-hive/files/root/setup.sh
prestodev/hdp3.1-hive/Dockerfile
prestodev/hdp3.1-hive/files/root/setup.sh
prestodev/iop4.2-hive/files/root/setup.sh

Hive 3 has `information_schema` (and `sys`) schemas
(https://issues.apache.org/jira/browse/HIVE-1010).
However, they need to be explicitly "installed".
Installation "instructions" are taken from a bug report
https://jira.apache.org/jira/browse/HIVE-16942.

Initiate information_schema, sys schemas in Hive

---

prestodev/hdp2.6-hive-kerberized-2/Dockerfile
prestodev/hdp2.6-hive-kerberized-2/files/etc/hadoop/conf/core-site.xml
prestodev/hdp2.6-hive-kerberized-2/files/etc/hadoop/conf/hdfs-site.xml
prestodev/hdp2.6-hive-kerberized-2/files/etc/hadoop/conf/mapred-site.xml
prestodev/hdp2.6-hive-kerberized-2/files/etc/hadoop/conf/yarn-site.xml
prestodev/hdp2.6-hive-kerberized-2/files/etc/hive/conf/hive-site.xml
prestodev/hdp2.6-hive-kerberized-2/files/etc/hive/conf/hiveserver2-site.xml
prestodev/hdp2.6-hive-kerberized-2/files/etc/krb5.conf
prestodev/hdp2.6-hive-kerberized-2/files/etc/supervisord.d/kdc.conf
prestodev/hdp2.6-hive-kerberized-2/files/var/kerberos/krb5kdc/kadm5-other.acl
prestodev/hdp2.6-hive-kerberized-2/files/var/kerberos/krb5kdc/kadm5.acl
prestodev/hdp2.6-hive-kerberized-2/files/var/kerberos/krb5kdc/kdc.conf

Setup another Kerberized HDP2.6 docker
This is useful when testing connection two differently kerberized
Hive servers from single Presto instance.

Setup another Kerberized HDP2.6 docker

---

prestodev/cdh5.12-hive/files/etc/supervisord.d/hive-metastore.conf
prestodev/cdh5.15-hive/files/etc/supervisord.d/hive-metastore.conf
prestodev/hdp2.5-hive/files/etc/supervisord.d/hive-metastore.conf
prestodev/hdp2.6-hive/files/etc/supervisord.d/hive-metastore.conf
prestodev/hdp3.1-hive/files/etc/supervisord.d/hive-metastore.conf

This is useful. Alternative obvious approach with setting `HADOOP_OPT`
requires manual modifications in the `hive` launcher script.

Add debugging instructions for Hive metastore

---

prestodev/hdp3.1-hive/files/etc/hadoop/conf/yarn-site.xml

That will prevent from containers being killed when they exceed physical memory limits and will (probably) remove some of the flakiness.

Disable physical memory checks for HDP3.1

---

prestodev/gpdb-6/Dockerfile
prestodev/gpdb-6/files/home/gpadmin/.bash_profile

This commit builds the latest Greenplum Database from source rather than using PPA's distribution which drops older versions of GPDB.  It also installs the `file_fdw` extension to be able to test foreign table support.

Source GPDB package from Github

---

prestodev/gpdb-6/Dockerfile
prestodev/gpdb-6/files/usr/local/bin/entrypoint.sh

Greenplum keeps track of the hostname in the metadata after initialization,
which can cause some issues as the hostnames change between Docker containers.
Here we add the original hostname when GPDB was initialized and add it to
/etc/hosts on startup so it can resolve that hostname.

Add original hostname to etc/hosts file for Greenplum

---

prestodev/accumulo/Dockerfile
prestodev/accumulo/files/etc/supervisord.conf
prestodev/accumulo/files/etc/supervisord.d/accumulo-gc.conf
prestodev/accumulo/files/etc/supervisord.d/accumulo-master.conf
prestodev/accumulo/files/etc/supervisord.d/accumulo-monitor.conf
prestodev/accumulo/files/etc/supervisord.d/accumulo-tracer.conf
prestodev/accumulo/files/etc/supervisord.d/accumulo-tserver.conf
prestodev/accumulo/files/etc/supervisord.d/zookeeper.conf

This commit adds an Accumulo 1.10.0 Docker image in order to remove the dependency on MiniAccumuloCluster in the presto-accumulo unit tests. It runs ZooKeeper and all five Accumulo services in the same container. While it isn't the "Docker way" to have multiple services in one container, it greatly simplifies use.

Add Accumulo Docker image

---

prestodev/centos6-oj8-openldap-referrals/files/etc/yum.repos.d/CentOS-Base.repo
prestodev/centos6-oj8-openldap/files/etc/yum.repos.d/CentOS-Base.repo
prestodev/centos6-oj8/files/etc/yum.repos.d/CentOS-Base.repo
prestodev/centos6-presto-admin-tests-runtime/Dockerfile
prestodev/centos6-presto-admin-tests-runtime/files/etc/yum.repos.d/CentOS-Base.repo

Since CentOS 6 went EOL packages were moved to https://vault.centos.org/

Switch to CentOS 6 Vault repositories

---

testing/spark3.0-iceberg/Dockerfile

Ref: https://github.com/trinodb/trino/pull/7049
Also pulled in the change from https://github.com/trinodb/docker-images/pull/67.
Built locally, `TestSparkCompatibility` succeeds.

Use Iceberg 0.11.0

---

.github/workflows/ci.yml

Previously it was missing and cause release to fail (due to dependency on removed CentOS 6: https://github.com/trinodb/docker-images/pull/95)

Build accumulo image on the CI

---

testing/cdh5.12-hive-kerberized/files/overrides/etc/hadoop/conf/core-site.xml
testing/cdh5.15-hive-kerberized-kms/files/etc/hadoop/conf/core-site.xml
testing/cdh5.15-hive-kerberized/files/overrides/etc/hadoop/conf/core-site.xml
testing/hdp2.6-hive-kerberized-2/files/overrides/etc/hadoop/conf/core-site.xml
testing/hdp2.6-hive-kerberized/files/overrides/etc/hadoop/conf/core-site.xml
testing/hdp3.1-hive-kerberized/files/overrides/etc/hadoop/conf/core-site.xml

This change broken OSS Trino automation for hive/hadoop impersonation tests.
It will need to be changed along with the new keytabs and certificates.

Restore previous presto-server proxyuser name

---

testing/cdh5.12-hive/Dockerfile
testing/centos7-oj8/Dockerfile
testing/hdp2.6-hive/Dockerfile
testing/hdp3.1-hive/Dockerfile
testing/kerberos/Dockerfile
testing/spark3.0-iceberg/Dockerfile

Reverts trinodb/docker-images#104
The PR was merged accidentally. Actuallty it was superseded with https://github.com/trinodb/docker-images/pull/105

Revert "Upgrade Zulu JDK to version 17"

---

testing/centos7-oj11/Dockerfile

`centos7-oj11`  image lacked `LANG` environment (as set in
`centos7-oj8`).  Locale defaulted to POSIX, which causes some tested
components to misbehave.

Fix locale setting

---

Makefile

`ghcr.io/trinodb/testing/hdp2.6-hive:47` was built using buildkit
and it's broken due to the `/root` directory being owned by `uid:gid` `502:20`
which prevents socks proxy from starting correctly.
```
docker history ghcr.io/trinodb/testing/hdp2.6-hive:46 | head -n 2
IMAGE          CREATED        CREATED BY                                      SIZE      COMMENT
223486d20623   7 days ago     /bin/sh -c #(nop)  LABEL io.trino.git.hash=5…   0B
```
```
docker history ghcr.io/trinodb/testing/hdp2.6-hive:47 | head -n 2
IMAGE          CREATED        CREATED BY                                      SIZE      COMMENT
9ec25b2bd57f   2 days ago     CMD ["/bin/sh" "-c" "supervisord -c /etc/sup…   0B        buildkit.dockerfile.v0
```

Disable buildkit when building docker images

---

testing/accumulo/Dockerfile
testing/hive3.1-hive/Dockerfile

https://github.com/trinodb/docker-images/pull/112 changed default JDK for those images from 8 to 11 which seems not to work. Restore JDK 8 as default JDK there.

Restore JDK 8 as default for hive3.1 and accumulo images

---

testing/spark3.0-iceberg/Dockerfile

In Trino:
```
testing/bin/ptl env up --environment 'singlenode-spark-iceberg'  --config 'config-default' 
```
```
docker container exec -it ptl-spark bash
cd ../bin
spark-sql
```
causes the following stacktrace:
```
22/01/17 16:41:48 WARN ShellBasedUnixGroupsMapping: unable to return groups for user hive
PartialGroupNameException The user name 'hive' is not found. id: hive: no such user
id: hive: no such user
at org.apache.hadoop.security.ShellBasedUnixGroupsMapping.resolvePartialGroupNames(ShellBasedUnixGroupsMapping.java:294)
at org.apache.hadoop.security.ShellBasedUnixGroupsMapping.getUnixGroups(ShellBasedUnixGroupsMapping.java:207)
at org.apache.hadoop.security.ShellBasedUnixGroupsMapping.getGroups(ShellBasedUnixGroupsMapping.java:97)
at …
```

Add hive user to the spark image

---

testing/cdh5.12-hive-kerberized/files/etc/krb5.conf
testing/cdh5.15-hive-kerberized/files/etc/krb5.conf
testing/hdp2.6-hive-kerberized-2/files/etc/krb5.conf
testing/hdp2.6-hive-kerberized/files/etc/krb5.conf
testing/hdp3.1-hive-kerberized/files/etc/krb5.conf
testing/kerberos/files/etc/krb5.conf

Some encryption types are now deprecated in JDK 17+ and will cause
Trino tests to fail. Enabling those types does not affect users in any
negative way as this applies only to testing infrastructure.
More details on introduced changes can be found under https://seanjmullan.org/blog/2021/09/14/jdk17

Allow weak encryption algorithms in Kerberos

---

testing/spark3.0-iceberg/Dockerfile

Relates to https://github.com/trinodb/trino/pull/11772

Add PostgreSQL JDBC driver jar to Iceberg image

---

testing/cdh5.12-hive-kerberized/Dockerfile
testing/cdh5.15-hive-kerberized/Dockerfile
testing/hdp2.6-hive-kerberized-2/Dockerfile
testing/hdp2.6-hive-kerberized/Dockerfile
testing/hdp3.1-hive-kerberized/Dockerfile

I want to cleanup and remove Presto references from the name of the containers in the product tests.

Add Trino principals and generate them for all workers

---

Makefile
testing/cdh5.12-hive/files/root/setup.sh
testing/cdh5.15-hive-kerberized-kms/files/root/setup_kms.sh
testing/cdh5.15-hive/files/root/setup.sh
testing/hdp2.6-hive/files/root/setup.sh
testing/hdp3.1-hive/files/root/setup.sh

Buildkit is faster and does caching better when building images.
In the near future, it will become a default docker build tooling.

Use buildkit while building images

---

.github/workflows/release.yml

Fixes release flow. See failure in https://github.com/trinodb/docker-images/runs/7802451805?check_suite_focus=true

Make sure VERSION is defined before trying to commit/tag

---

.github/workflows/release.yml

git log was being used to verify whether the tag exists and points to
correct commit and to see whether the version bump commit was correct.
Both usages are now replaced with more appropriate commands to reduce
noise from large git log output in CI logs.

Replace git log with more targeted commands in release flow

---

testing/spark3-delta/Dockerfile

Upgrade the delta library to the version `2.1.0`.
As described in https://docs.delta.io/latest/releases.html this version depends on Spark 3.3.x which can run _on Java 8/11/17, Scala 2.12/2.13_ as described by https://spark.apache.org/docs/3.3.0/

Bump delta to version `2.1.0`

---

.github/workflows/ci.yml
bin/depend.sh
bin/flag.sh
bin/push.sh
bin/test.sh
etc/compose/accumulo/docker-compose.yml
etc/compose/dns/docker-compose.yml
etc/compose/openldap/docker-compose.yml
etc/compose/spark3-delta/docker-compose.yml
etc/compose/spark3-iceberg/docker-compose.yml
testing/centos7-oj11/Dockerfile
testing/centos7-oj11/files/opt/trinodev/site-override.xslt
testing/centos7-oj11/files/usr/local/bin/apply-all-site-xml-overrides
testing/centos7-oj11/files/usr/local/bin/apply-site-xml-override
testing/dns/Dockerfile
testing/phoenix5/Dockerfile
testing/spark3-delta/Dockerfile
testing/spark3-iceberg/Dockerfile

Extracted from #143 
Partially reverts #140 - restore using JDK 11 for Spark and Phoenix images. Tests were failing without this. This was also raised in https://github.com/trinodb/trino/pull/13733

Add tests for all images

---

.github/workflows/ci.yml
etc/compose/spark3-hudi/docker-compose.yml
testing/spark3-hudi/Dockerfile

Add spark3-hudi image for product tests
- Installs Spark 3.2.1
- Installs hudi-spark3-bundle
- Add Hive user

Add spark3-hudi image

---

.github/workflows/ci.yml
.github/workflows/release.yml
Makefile
bin/build.sh
bin/depend.sh
bin/lib.sh
bin/push.sh
bin/tag.sh
bin/test.sh
etc/compose/accumulo/docker-compose.yml
etc/compose/dns/docker-compose.yml
etc/compose/hive3.1-hive/docker-compose.yml
etc/compose/kerberos/docker-compose.yml
etc/compose/openldap/docker-compose.yml
etc/compose/spark3-delta/docker-compose.yml
etc/compose/spark3-hudi/docker-compose.yml
etc/compose/spark3-iceberg/docker-compose.yml
testing/accumulo/Dockerfile
testing/centos7-oj11/Dockerfile
testing/centos7-oj17-openldap-referrals/Dockerfile
testing/centos7-oj17-openldap/Dockerfile
testing/centos7-oj17/Dockerfile
testing/hive3.1-hive/Dockerfile
testing/kerberos/Dockerfile
testing/phoenix5/Dockerfile
testing/spark3-delta/Dockerfile
testing/spark3-hudi/Dockerfile
testing/spark3-iceberg/Dockerfile

This is an alternative to #138
This PR wrap calls to `docker build`, `docker tag`, and `docker push` with scripts that recognize the `PLATFORMS` env var. If it's set, a separate image for every architecture is used. After pushing all images, a manifest is created.

Build multi-arch images if PLATFORMS env var is set

---

.github/workflows/release.yml
bin/push.sh

I spotted and fixed two issues:
* `bin/push.sh` didn't correctly check if `PLATFORMS` is set
* the release workflow didn't call `make` and `bin/push.sh` with correct value of `PLATFORMS`

Fix releases with multiarch images

---

.github/workflows/release.yml

It is required when running `make` with `linux/arm64` in `PLATFORMS` on non-arm Github runners (the only kind available).

Setup QEMU in the release workflow to build multiarch images

---

bin/test.sh
testing/spark3-delta/Dockerfile
testing/spark3-hudi/Dockerfile
testing/spark3-iceberg/Dockerfile

This was useful for me to make sure if it's the Spark image being broken itself or some runtime issue when debugging issues in https://github.com/trinodb/trino/pull/14810

Add proper tests for Spark images

---

testing/hdp3.1-hive/files/etc/hive/conf/hive-site.xml
testing/hive3.1-hive/files/opt/hive/conf/hive-site.xml

This would make Hive 2 and Hive 3 to have similar restriction for column type changes.
In case of hive2 - the default value of an equivalent property  hive.metastore.disallow.incompatible.col.type.changes is false.
Preparatory PR for https://github.com/trinodb/trino/pull/15898

Relax Hive-3 column datatype changes

---

testing/cdh5.15-hive-kerberized-kms/files/usr/bin/extract_rpms.sh

Replace the download url since it was failing with 403 error code. 
Ref : https://github.com/trinodb/docker-images/actions/runs/5395681704/jobs/9798411645?pr=166

Update download url for rpmrebuild

---

testing/hive3.1-hive/Dockerfile

Previous URL was taking too long to download hive binary. 
Now the build time for hive-3.1 was reduced from 2h+ to around 20-30mins.

Update download url for hive binary

---

.github/workflows/release.yml

`centos7-oj17-openldap-base` is a base image whose scope is only for building `openldap` and `active-directory` so we could skip release process for the base image

Allow base image to be skipped during release

---

.github/workflows/release.yml

[Latest release](https://github.com/trinodb/docker-images/actions/runs/6089349336) failed because of the new image added in #172. Add it to the single arch images list.

Add missing image to single arch images list

---

.github/workflows/release.yml

After adding a new single arch image, the release failed after running out of disk space on the workflow runner node. Clean up some space after building single arch images.

Free up some disk space during releases

---

.github/workflows/release.yml

The previous attempt in #174 to free up disk space during release was wrong, as it did pruning between pushing images, not between building them for single vs multi arch. Do it earlier, but only remove dangling (untagged) images. This also removes dangling build cache.

Prune only dangling images during release

---

testing/centos7-oj11/Dockerfile
testing/centos7-oj17/Dockerfile

This updates ca-certificates that allow us to connect to archive.apache.org securely.

Update base centos7 images

---

testing/accumulo/Dockerfile
testing/accumulo/files/etc/accumulo.properties
testing/accumulo/files/etc/supervisord.d/accumulo-gc.conf
testing/accumulo/files/etc/supervisord.d/accumulo-manager.conf
testing/accumulo/files/etc/supervisord.d/accumulo-master.conf
testing/accumulo/files/etc/supervisord.d/accumulo-monitor.conf
testing/accumulo/files/etc/supervisord.d/accumulo-tracer.conf
testing/accumulo/files/etc/supervisord.d/accumulo-tserver.conf

Verified locally with the updated connector. All tests are passing.

Update accumulo to 3.0.0

---

.github/workflows/ci.yml

The job failed after 6 hours in https://github.com/trinodb/docker-images/actions/runs/8259379627/job/22593193755?pr=190. It would be nice to set timeout. 
I chose 60 minutes because `ci / build-images (hive3.1-hive, linux/amd64,linux/arm64, hive3.1-hive) (push)` took 40 minutes in https://github.com/trinodb/docker-images/actions/runs/7921889852/job/21628209184

Set timeout for build-images

---

testing/spark3-iceberg/Dockerfile

To run Iceberg product tests with MinIO like OSS Delta Lake.

Install AWS SDK on Iceberg image

---

testing/centos7-oj11/Dockerfile
testing/centos7-oj17/Dockerfile
testing/hive3.1-hive/Dockerfile

```
Could not fetch URL https://pypi.python.org/simple/supervisor/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618) - skipping
Could not find a version that satisfies the requirement supervisor (from versions: )
```

Fix ssl certificate error and broken Hive download link

---

testing/spark3-iceberg/Dockerfile

Modify the spark testing image to include Azure and Google cloud storage hadoop dependency jars to enable querying their object stores

Modify spark image to include azure and gcs dependency jars

---

.github/workflows/ci.yml
.github/workflows/release.yml
bin/test.sh
etc/compose/polaris-catalog/docker-compose.yml
testing/polaris-catalog/Dockerfile

This is a temporal solution until the Polaris community publishes the official image.

Add Polaris catalog docker image

---

.github/workflows/ci.yml
bin/test.sh
etc/compose/unity-catalog/docker-compose.yml
testing/unity-catalog/Dockerfile

Add temporary docker image until Unity catalog publish their image: https://github.com/unitycatalog/unitycatalog
Manual confirmation:
```sh
➜  docker-images git:(ebi/unity-catalog) docker run -p 8080:8080 testing/unity-catalog
###################################################################
###################################################################
➜  docker-images git:(ebi/unity-catalog) curl http://localhost:8080
Hello, Unity Catalog!%
```

Add Unity catalog docker image

---

.github/workflows/release.yml

Fix failing release job: https://github.com/trinodb/docker-images/actions/runs/11271512937
```
Images that would not get released: testing/unity-catalog
Must be explicitly added to either single_arch or multi_arch list or should be added to skipped list
```

Move polaris-catalog to multi_arch + Add unity-catalog to release job

---

testing/hive3.1-hive/Dockerfile

The job is failing on master because 3.1.3 no longer exists in https://dlcdn.apache.org/hive. 
```
#8 ERROR: process "/bin/sh -c curl -fLsS -o /tmp/hive.tar.gz --url $HIVE_BINARY_PATH &&     tar xzf /tmp/hive.tar.gz --directory /opt && mv /opt/apache-hive-${HIVE_VERSION}-bin /opt/hive" did not complete successfully: exit code: 22
------
> [ 4/10] RUN curl -fLsS -o /tmp/hive.tar.gz --url https://dlcdn.apache.org/hive/hive-3.1.3/apache-hive-3.1.3-bin.tar.gz &&     tar xzf /tmp/hive.tar.gz --directory /opt && mv /opt/apache-hive-3.1.3-bin /opt/hive:
0.583 curl: (22) The requested URL returned error: 404
------
```
https://github.com/trinodb/docker-images/actions/runs/11271958170/job/31345890289

Use archive.apache.org domain for Apache Hive

---

testing/unity-catalog/Dockerfile

Trino CI started failing after https://github.com/trinodb/docker-images/pull/214. Polaris change looks fine. 
I tried other approaches, but couldn't reduce the size without breaking the image.

Revert reducing image size of Unity catalog

---

testing/polaris-catalog/Dockerfile

With the the recent module breakdown(https://github.com/apache/polaris/pull/523) in Polaris repo, update Polaris Dockerfile with renamed Polaris executable jar location.

Fix Polaris image

---

.github/workflows/ci.yml
.github/workflows/release.yml
bin/test.sh
etc/compose/hive4.0-hive/docker-compose.yml
testing/hive4.0-hive/Dockerfile

Build custom hive4 image with access to S3 by using plain apache [hive4 image](https://hub.docker.com/r/apache/hive). Plain hive image offers an advantage of not having to tweak multiple configuration. However, currently created image doesn't include yarn services which will be required to run queries concurrently. We may need to build a new image to accommodate yarn services as we run different tests using Hive4.

Add hive 4.0 image

---

.github/workflows/release.yml

Fix release failure: https://github.com/trinodb/docker-images/actions/runs/13324166494/job/37213954877

Add Polaris and Unity to skipped_images

---

.github/workflows/release.yml

I accidentally removed the line in https://github.com/trinodb/docker-images/pull/223/files#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L94

Restore testing/hive4.0-hive in release.yml

---

.github/workflows/ci.yml
.github/workflows/release.yml

Release job is still failing: https://github.com/trinodb/docker-images/actions/runs/13324968118/job/37216185043
Relates to https://github.com/docker/setup-qemu-action/issues/198

Pin QEMU version temporarily

---

.github/workflows/ci.yml
.github/workflows/release.yml
testing/polaris-catalog/Dockerfile

Fix [Polaris build failure](https://github.com/trinodb/docker-images/actions/runs/13623035426/job/38075621405?pr=228) and reenable Polaris and Unity catalogs.

Reenable Polaris and Unity catalogs

---

testing/polaris-catalog/Dockerfile

I confirmed this change fixes TestIcebergPolarisCatalogConnectorSmokeTest failure in Trino repository

Fix Polaris initialization failure

---

Makefile

This breaks release as it's using `make list` to check whether all single and multi arch images are released.

Remove relative path prefix

---

etc/compose/hdp3.1-hive/docker-compose.yml
etc/compose/hive3.1-hive/docker-compose.yml
etc/compose/hive4.0-hive/docker-compose.yml
etc/compose/kerberos/docker-compose.yml
etc/compose/openldap-active-directory/docker-compose.yml
etc/compose/openldap/docker-compose.yml
etc/compose/polaris-catalog/docker-compose.yml
etc/compose/spark3-hudi/docker-compose.yml
etc/compose/spark3-iceberg/docker-compose.yml
etc/compose/spark4-delta/docker-compose.yml
etc/compose/unity-catalog/docker-compose.yml

Fix the following warning:
```
WARN[0000] /home/runner/work/docker-images/docker-images/etc/compose/openldap/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
```

Remove obsolete version attribute
